// import { Routes, Route, Router } from "react-router-dom";

// import IndexPage from "./pages/HomePage/IndexPage";
// import ContactPage from "./pages/ContactPage/ContactPage";
// import NotFound from "./pages/PageNotFound/NotFoundPage";
// import GalleryPage from "./pages/GalleryPage/GalleryPage";
// import BlogPage from "./pages/BlogPage/BlogPage";
// import PythonCourse from "./pages/CoursePage/Python-course";
// import DataScienceCourse from "./pages/CoursePage/DataScience";
// import DataAnalyticsCourse from "./pages/CoursePage/DataAnalytics";
// import PowerBiCourse from "./pages/CoursePage/PowerBi";
// import InformaticaCourse from "./pages/CoursePage/Informatica";
// import AwsCourse from "./pages/CoursePage/Aws";
// import AzureCourse from "./pages/CoursePage/Azure";
// import PegaCourse from "./pages/CoursePage/Pega";
// import MicrosoftCourse from "./pages/CoursePage/Microsoft";
// import JavaCourse from "./pages/CoursePage/Java";
// import TestingCourse from "./pages/CoursePage/Testing";
// import SapCourse from "./pages/CoursePage/Sap";
// import TableauCourse from "./pages/CoursePage/Tableau";

// function App() {
//   // const sendMail = () => {
//   //   console.log("something");
//   // };
//   // const openForm = () => {
//   //   console.log("something");
//   // };
//   // const closeForm = () => {
//   //   console.log("something");
//   // };
//   return (
//     <div>
//       <Router>
//         <div>
//           {" "}
//           <Routes>
//             <Route path="/" element={<IndexPage />} />
//             <Route path="/home" element={<IndexPage />} />
//             {/* <Route path="/about#about-section" /> */}
//             <Route path="/contact" element={<ContactPage />} />
//             <Route path="/gallery" element={<GalleryPage />} />
//             <Route path="/blog" element={<BlogPage />} />
//             <Route
//               path="/python-course"
//               element={<PythonCourse prop="Python Course" />}
//             />
//             <Route
//               path="/DataScience"
//               element={
//                 <DataScienceCourse prop="Data Science With AI & ML Course" />
//               }
//             />
//             <Route
//               path="/DataAnalytics"
//               element={<DataAnalyticsCourse prop="Data Analytics" />}
//             />

//             <Route
//               path="/PowerBi"
//               element={<PowerBiCourse prop="Power BI" />}
//             />
//             <Route
//               path="/Informatica"
//               element={<InformaticaCourse prop="Informatica" />}
//             />
//             <Route path="/Aws" element={<AwsCourse prop="AWS DEVOPS" />} />
//             <Route
//               path="/Azure"
//               element={<AzureCourse prop="AZURE DEVOPS" />}
//             />
//             <Route path="/Pega" element={<PegaCourse prop="PEGA" />} />
//             <Route
//               path="/MicroSoft"
//               element={<MicrosoftCourse prop="MICROSOFT FULL STACK" />}
//             />
//             <Route
//               path="/Java"
//               element={<JavaCourse prop="JAVA FULL STACK" />}
//             />
//             <Route
//               path="/Testing"
//               element={<TestingCourse prop="TESTING MANUAL & AUTOMATION" />}
//             />
//             <Route
//               path="/Sap"
//               element={<SapCourse prop="SAP FICO WITH S4 HANA" />}
//             />
//             <Route
//               path="/Tableau"
//               element={
//                 <TableauCourse
//                   prop="Tableau
// "
//                 />
//               }
//             />
//             <Route path="*" element={<NotFound />} />
//           </Routes>{" "}
//         </div>
//       </Router>
//     </div>
//   );
// }

// export default App;
import { Routes, Route } from "react-router-dom";

import IndexPage from "./pages/HomePage/IndexPage";
import ContactPage from "./pages/ContactPage/ContactPage";
import NotFound from "./pages/PageNotFound/NotFoundPage";
import GalleryPage from "./pages/GalleryPage/GalleryPage";
import BlogPage from "./pages/BlogPage/BlogPage";
import PythonCourse from "./pages/CoursePage/Python-course";
import DataScienceCourse from "./pages/CoursePage/DataScience";
import DataAnalyticsCourse from "./pages/CoursePage/DataAnalytics";
import PowerBiCourse from "./pages/CoursePage/PowerBi";
import InformaticaCourse from "./pages/CoursePage/Informatica";
import AwsCourse from "./pages/CoursePage/Aws";
import AzureCourse from "./pages/CoursePage/Azure";
import PegaCourse from "./pages/CoursePage/Pega";
import MicrosoftCourse from "./pages/CoursePage/Microsoft";
import JavaCourse from "./pages/CoursePage/Java";
import TestingCourse from "./pages/CoursePage/Testing";
import SapCourse from "./pages/CoursePage/Sap";
import TableauCourse from "./pages/CoursePage/Tableau";
import HomePage from "./pages/HomePage/HomePage";
import AOS from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";
import OurCoursesPage from "./pages/CoursesPage/OurCoursesPage";
import AboutUsPage from "./pages/AboutPage/AboutUsPage";
import SqlCourse from "./pages/CoursePage/Sql";
function App() {
  useEffect(() => {
    AOS.init();
  }, []);
  const Sap = {
    title: "SAP FICO WITH S4 HANA",
    part1: "PART-1 (GENERAL LEDGER ACCOUNTING)",
    topic1: [
      "FUNDAMENTALS OF ACCOUNTING",
      "ACCOUNTING CYCLE",
      "SAP FI/CO ORGANIZATIONAL STRUCTURE",
      "SAP FI GLOBAL SETTINGS",
      "GENERAL LEDGER ACCOUNTING",
      "CHART OF ACCOUNTS",
      "ACCOUNT GROUPS",
      "RETAINED EARNING ACCOUNT",
      "GENERAL LEDGER MASTERDATA",
    ],
    part2: "PART-2(NEW GENERAL LEDGER ACCOUNTING)",
    topic2: [
      "LEADING AND NON LEADING LEDGERS",
      "CURRENCY SETTINGS",
      "DOCUMENT SPLITTING",
    ],
    part3: "PART-3(ACCOUNTS PAYABLES AND RECEIVABLES)",
    topic3: [
      "ACCOUNTS PAYABLES & RECEIVABLES BASIC CONCEPTS",
      "ACCOUNTS PAYABLES & RECEIVABLES SPECIAL G/L SCENARIOS",
      "ACCOUNTS PAYABLES & RECEIVABLES WITH PAYMENT TERMS",
    ],
    part4: "PART- 4 (FOREIGN CURRENCY REVALUATION)",
    topic4: [
      "BASICS OF FOREIGN CURRENCY REVALUATION",
      "FOREIGN CURRENCY REVALUATION WITH VENDOR OPEN ITEM",
      "FOREIGN CURRENCY REVALUATION WITH CUSTOMER OPEN ITEM",
      "VENDOR AND CUSTOMER WITH PAYMENT POSTING WITH FORIGN CURRENCY",
    ],
    part5: "PART-5 (TAX ACCOUNTING)",
    topic5: [
      "WITH HOLDING TAX AND EXTENDED WITHHOLDING TAX (TDS)",
      "TAX ON SALES & PURCHASES (GST)",
      "ACCOUNTS PAYABLES & RECEIVABLES WITH PAYMENT TERMS",
    ],
    part6: "PART – 6 (BANK ACCOUNTING & DUNNING)  ",
    topic6: [
      "HOUSE BANK",
      "HOUSE BANK",
      "APP WITH DME FILE",
      "APP WITH IDOC",
      "FOREIGN CURRENCY WITH APP",
      "MANUAL BANK STATEMENT(MBS)",
      "ELECTRONIC BANK STATEMENT (EBS)",
      "DUNNING",
    ],
    part7: "PART-7(ASSET ACCOUNTING)",
    topic7: [
      "CHART OF DEPRECIATION AND DEPRECIATION AREA",
      "ASSET CLASS",
      "DEPRECIATION KEY",
      "ASSET MASTER",
      "ASSET LIFE CYCLE",
    ],
    part8: "PART-8 (CROSS MODULE INTEGRATION)",
    topic8: ["MM-FI INTEGRATION", "SD-FI INTEGRATION"],
    part9: "PART-9(CONTROLLING)",
    topic9: [
      "BASICS OF CONTROLLING",
      "COST ELEMENT ACCOUNTING",
      "COST CENTER ACCOUNTING",
      "INTERNAL ORDER",
      "PROFIT CENTER ACCOUNTING",
    ],
    part10: "PART-10 (S4 HANA FINANCE)",
    topic10: [
      "LEDGERS AND CURRENCIES",
      "DETAILS OF UNIVERSAL JOURNAL",
      "BUSINESS PARTNER FOR VENDORS AND CUSTOMERS",
      "HOUSE BANK WITH FIORI APP",
      "NEW ASSET ACCOUNTING",
    ],
    part11: "PART-11 (PROJECT)",
    topic11: [
      "REAL TIME PROJECTS",
      "Implementation project",
      "Brown field implementation project",
      "Support project with ticketing tools",
      "Rollout Project",
      "RESUME PREPARATION",
      "MOCK INTERVIEWS",
    ],
  };

  const pythonData = {
    title: "Python Programming",
    part1: "Python Programming",
    topic1: [
      " What is Python?",
      "History",
      "Why is Python preferred for Data Science?",
      "Installation of I python/Jupyter Notebook/ SPYDER",
    ],
    part2: "Basics of Python:",
    topic2: [
      "Keywords",
      "Built-in functions",
      "String Formatting Lists",
      "Loops ",
      "Tuples",
      "Indexing",
      "Slicing",
      "Sequences",
      "Dictionaries",
      "Sets",
      "Importing and exporting data from python into various formats",
    ],
    part3: "Functions",
    topic3: [
      "User defined functions ",
      "Parameters",
      "Nested functions",
      "Local and Global variables",
      "Alternative Keys",
      "Lambda functions",
      "Sorting Lists and Dictionaries",
      "Sorting Collections",
    ],
    part4: "OOPS",
    topic4: [
      "Methods and Inheritance",
      "Abstraction and Encapsulation",
      "Classes",
      "Walking Directory Trees",
      "Initializes",
      "Instance methods",
      "lass methods",
      "Data Static Methods ",
      "Expressions",
      "Module Aliases ",
      "Math functions",
      "Random Numbers",
      "Package Installation Methods",
      "Introduction to Numpy, Pandas and other libraries ",
      "Plotting in Python ",
      "Creating Data Frames ",
      "Data Manipulation ",
      "Slicing and Dicing",
    ],
    part5: "Error and Exception handling",
    topic5: [
      "Errors in Python",
      "Abnormal termination",
      "Exception handling methods ",
      "Ignoring Errors",
      "Assertions and effective ",
      "usage of assertions",
    ],
    part6: "Modules",
    topic6: [
      "Pre defined /Built in modules",
      "User defined modules",
      "How to import a module",
    ],
    part7: "Data Types: (In Detail)",
    topic7: [
      "List",
      "Tuple",
      "Set",
      "Dicts",
      "Dicts",
      "ontrol Flows",
      "Loops",
      " *Minimum 3 Practical Session for control flows and Loops",
    ],
  };
  const DataScience = {
    title: "Data Science (ML, AI, Python, Tableau)",
    part1: "Introduction to Data Science",
    topic1: [
      "What is Data Science?",
      "What is Machine Learning?",
      "Who are Data Scientists?",
      "What skills are required to become a Data Scientist?",
      "Why should a data scientist learn both R as well as Python?",
      "Is there an importance for Statistics in Data Science?",
      "Where do we implement Data Science in real time?",
      "In which sectors of business do we implement Data Science?",
      "What kind of projects do Data Scientists work on?",
      "Each and every technique explained with a real-time example",
      "What is the difference between Machine Learning, AI, and Deep Learning?",
    ],
    part2: "Business Statistics",
    topic2: [
      "DATA TYPES",
      "Continuous Variables",
      "Ordinal Variables",
      "Categorical Variables",
      "Time Series",
      "Miscellaneous",
      "Descriptive Statistics",
      "Sampling",
      "Random Sampling",
      "Systematic Sampling",
      "Stratified Sampling",
      "Data Distributions",
      "Normal Distribution",
      "Binomial Distribution",
      "Weibull Distribution",
      "Poisson Distribution",
      "Exponential Distribution",
      "Central Tendencies",
      "Mean, Median, Mode",
      "Standard Deviation",
      "Probabilities",
      "Variance",
      "Plotting",
      "Basic and Business Statistics",
      "Distance Formulas",
      "Similarities",
      "Minkowski Distance",
      "L1 Norm",
      "Lmin Norm",
      "Manhattan Distance",
      "Taxi Cab",
      "Supremum",
      "Lmax Norm",
      "Euclidean Distance",
      "Cosine Similarity",
      "Hamming Distance",
      "Levenshtein Distance",
      "Simple Matching Coefficients",
      "Jaccard's Equation",
      "Differences between Distances and Similarities",
      "Product of Dot Vectors",
      "Binary Values",
      "Mahalanobis Distance",
      "Matrix Multiplication",
      "Variance",
      "Conditional Probabilities",
      "Difference between Statistics and Probability",
      "Confusion Matrix",
      "Error Types",
      "Mean Squared Error",
      "Root Mean Square Error",
      "Accuracy Measures",
    ],
    part3: "Introduction to Machine Learning and AI",
    topic3: [
      "How to deal with a prediction problem",
      "How to apply different forecasting techniques",
      "Supervised Learning",
      "Unsupervised Learning",
      "Optimization",
      "Sentiment Analysis",
      "Statistical Modelling",
    ],
    part4: "Machine Learning - Statistical Modelling",
    topic4: [
      "Simple Linear Regression",
      "Simple Linear Regression with Gradient Descent",
      "Linear Regression with Quadratic Equation",
      "Stochastic Gradient Descent Model",
      "Error Minimization Model",
      "Linear Regression for Classification",
      "Estimating the Coefficients",
      "Assessing the Accuracy of the Coefficient Estimates",
      "Multiple Linear Regression",
      "Finding a New Dependent Variable as Prediction",
      "How to Find Slope and Intercept",
    ],
    part5: "Logistic Regression and Advanced Models",
    topic5: [
      "Logistic Regression",
      "Spline Regression",
      "Sigmoid, Ridge, and Lasso Regression",
      "The Logistic Model",
      "Making Predictions",
      "Multiple Logistic Regression",
      "Non-Linear Regression",
    ],
    part6: "Linear Discriminant Analysis",
    topic6: [
      "Exploratory Data Analysis",
      "Single Variant Model Analysis",
      "Multi-Variant Model Analysis",
      "Quadratic Discriminant Analysis",
    ],
    part7: "Naive Bayes and Support Vector Machines",
    topic7: [
      "Naive Bayes",
      "Support Vector Machines",
      "Maximum Margin Classifier",
      "What is a Hyperplane?",
      "What are Marginal Hyperplanes?",
      "Classification using a Separating Hyperplane",
      "SVM Linear Model",
      "SVM Non-Linear Model",
      "SVM Kernel Method",
      "SVM Power Kernel Method",
    ],
    part8: "K-Nearest Neighbors (KNN)",
    topic8: [
      "Advantages of KNN",
      "Disadvantages of KNN",
      "How to Find an Appropriate K Value?",
      "How to Use KNN for Classification?",
      "How to Use KNN for Regression?",
      "How to Find the Nearest Neighbor",
    ],
    part9: "Ensemble Learning and Random Forest",
    topic9: [
      "Ada-Boost / Adaptive Boosting",
      "Random Forest",
      "Overview of Random Forests",
      "Classification with Random Forests",
      "Implementation of Random Forests",
    ],
    part10: "Decision Trees and Extra Trees",
    topic10: [
      "How to Build a Decision Tree",
      "What is Classification and Its Uses?",
      "What is a Decision Tree?",
      "Creating a Decision Tree",
      "Information Entropy",
      "Information Gain",
      "Examples",
      "Gini Index and Entropy Methods",
    ],
    part11: "Market Basket Analysis and Association Rules",
    topic11: [
      "Market Basket Analysis",
      "Characteristics of Market Basket Analysis",
      "Applications of Market Basket Analysis",
      "Association Rules",
    ],
    part12: "Forecasting Analysis",
    topic12: [
      "Why Forecasting?",
      "Features Common to All Forecasts",
      "Elements of a Good Forecast",
      "Types of Forecasts",
      "Qualitative Methods",
      "Quantitative Methods",
      "Techniques for Averaging",
      "Techniques for Trend",
      "Techniques for Seasonality",
      "Seasonalizing Trend",
      "De-seasonalizing Trend",
      "Predictive Analysis",
      "Various Approaches to Solve a Problem",
    ],
    part13: "Re-Sampling and Ensembling Techniques",
    topic13: ["Bagging", "Boosting", "RF Techniques"],
    part14: "Gradient Boosting and Clustering",
    topic14: [
      "Gradient Boosting Method",
      "Trees for Prediction",
      "Trees for Classification",
      "K-means Clustering",
      "Clustering Techniques",
      "Hierarchical Clustering",
    ],
    part15: "Time Series Forecasting",
    topic15: [
      "Qualitative Methods",
      "Quantitative Methods",
      "Moving Averages",
      "Smoothing Techniques",
      "Exponential Smoothing",
      "Weighted Moving Averages",
      "ARMA",
      "ARIMA",
      "Trend and Seasonality Forecasting",
      "Linear, Quadratic, Exponential Forecasting",
      "Auto Regressive",
    ],
    part16: "Semi-Supervised and Reinforcement Learning",
    topic16: ["Semi-Supervised Learning", "Reinforcement Learning"],
    part17: "Miscellaneous",
    topic17: [
      "Taxonomy Creation",
      "Sentiment Analysis",
      "Text Classification Models",
      "Process of Tree Building",
      "Problem of Underfitting",
      "Problem of Overfitting",
      "Pruning a Tree Back",
    ],
    part18: "Python for Data Science",
    topic18: [
      "Introduction to Python",
      "Basics of Python",
      "Number Systems",
      "Operators",
      "Loops",
      "Functions",
      "Lists",
      "Tuples",
      "Sets",
      "Dictionaries",
      "Why Python for Data Science",
      "Data Munging with Python",
      "Introduction to Pandas, Numpy",
      "Data Loading with Pandas",
      "Descriptive Statistics with Pandas",
      "Sort, Merge, Join with Pandas",
      "Getting to Understand Structure of Matplotlib",
      "Different Plotting Techniques",
      "Correlation Matrix Plotting",
      "Indexing and Slicing with Pandas",
      "Grid Search",
      "Pre-processing Techniques",
      "Model Validation",
      "Deployment",
    ],
    part19: "Metrics and Miscellaneous Topics",
    topic19: [
      "Feed Forward Neural Network",
      "Elman Neural Network",
      "Jordan Neural Network",
      "Weight Initialization",
      "Learning Rate Calculation",
      "Self-Connected Neural Network",
      "Recurrent Neural Network",
      "Convolution Neural Networks",
      "Long Short-Term Memory",
      "ReLU",
      "ELU",
      "PRELU",
      "Image Processing",
    ],
    part20: "Practical Use Case of How to Implement Prediction Models on Data",
    topic20: [
      "How to Define a Problem / Prepare the Problem",
      "Load the Libraries",
      "Load the Respective Data Set",
      "How to Summarize the Data",
      "Descriptive Statistics",
      "Data Visualization",
      "How to Prepare the Data",
      "Data Cleaning",
      "Feature Selection",
      "Data Transformations",
      "How to Evaluate Algorithms",
      "Split-out Validation Datasets",
      "Test Options and Evaluation Metrics",
      "Spot Check Algorithms",
      "Compare Algorithms",
      "How to Improve Accuracy/Results",
      "Algorithm Tuning",
      "Using Ensembling Techniques",
      "How to Print Results",
      "How to Finalize the Model",
      "Predictions on Validation Dataset",
    ],
    part21: "Machine Learning (Both Semantics and Syntax)",
    topic21: [
      "We Teach All Algorithms Not Only in Python and R, but We Teach All the Back-End Process in MS-Excel Also",
      "Python-pandas, numpy, matplotlib, scipy, sklearn, keras, tensorflow",
    ],
  };

  const DataAnalytics = {
    title: "Data Analytics",
    part1: "Introduction to Data Analytics",
    topic1: [
      "Data Analytics using Excel",
      "Basics of Excel",
      "Functions in Excel - Text, Date,Logical",
      "Conditional Formatting",
      "Sorting and Filtering",
      "Subtotal, Group and Ungroup",
      "Pivot Table",
    ],
    part2: "Working with text, removing duplicates",
    topic2: [
      "Lookup-Vlookup, Hlookup,X-Loop,/ndex, Match",
      "Data Validation - List, Dependency List",
      "What if analysis",
      "Data Analysis",
      "Power Query",
      "Dashboards",
      "Solver",
      "Forecast",
    ],
    part3: "SQL",
    topic3: [
      "Introduction to SQL",
      "DDL Commands-CREATE,ALTER,DROP, TRUNCATE,RENAME",
      "Constraints - NOT NULL, UNIQUE,PRIMARY KEY,FOREIGN KEY,CHECK",
      "DML Commands - INSERT, UPDATE,DELETE",
      "DTL Commands",
      "DCL Commands - GRANT , REVOKE",
      "Select Query",
      "Joins",
      "Different operators",
      "Sub Query",
    ],
    part4: "Python",
    topic4: [
      "Installation",
      "Data Types - Number, String,Sequence-String, List, Tuple, Sets, Dictionaries",
      "Conditional Statements",
      "Control Flow - For loop , While Loop",
      "Functions",
      "Module and Packages",
      "File Handling -text,csv,excel",
      "Connecting with SQL",
      "Numpy",
      "Pandas",
      "Data Visualization using Matplotlib",
      "Webscraping - Regex",
    ],
    part5: "Power BI",
    topic5: [
      "Introduction to Power BI",
      "Loading data from different file formats",
      "Transformation using Power Query Editor",
      "Data Visualization",
      "Data Modelling",
      "DAX",
      "Optimization",
      "Al Visuals",
      "Dashboards",
    ],
    part6: "Tableau",
    topic6: [
      "Introduction to Tableau",
      "Connecting to different file formats",
      "Tableau basic reports",
      "Tableau advanced charts",
      "Calculations, Filters,Groups, Parameters",
      "Dashboards & Story",
    ],
  };
  const PowerBi = {
    title: "Power BI Course",
    part1: "SQL SERVER INTRODUCTION",
    topic1: [
      "Data, Databases and RDBMS Software",
      "Database Types: OLTP, DWH, OLAP",
      "Microsoft SQL Server Advantages, Use",
      "Versions and Editions of SQL Server",
      "SQL: Purpose, Real-time Usage Options",
      "SQL versus Microsoft T-SQL [MSSQL]",
      "Microsoft SQL Server - Career Options",
      "SQL Server Components and Usage",
      "Database Engine Component and OLTP",
      "BI Components, Data Science Components",
      "ETL, MSBI and Power BI Components",
      "Course Plan, Concepts, Resume, Project",
      "24x7 Online Labs for Remote DB Access",
      "Software Installation Pre-Requisites",
    ],
    part2: "Introduction to Power BI (Free Demo Class)",
    topic2: [
      "Power BI Job Roles in Real-time",
      "Power BI Data Analyst Job Roles",
      "Business Analyst - Job Roles",
      "Power BI Developer - Job Roles",
      "Power BI for Data Scientists",
      "Comparing MSBI and Power BI",
      "Comparing Tableau and Power BI",
      "MCSA 70-778, MCSA 70-779 Exam",
      "Types of Reports in Real-World",
      "Interactive & Paginated Reports",
      "Analytical & Mobile Reports",
      "Data Sources Types in Power BI",
      "Power BI Licensing Plans - Types",
      "Power BI Training : Lab Plan",
      "Power BI Dev & Prod Environments",
      "Understanding the Power BI Tools",
      "Installing Power BI & Connecting to Data",
      "The 'Locale' used in the curriculum",
      "Working with the query Editor",
      "Working with the data model and creating a visualization",
    ],
    part3: "Basic Report Design",
    topic3: [
      "Power BI Desktop Installation",
      "Data Sources & Visual Types",
      "Canvas, Visualizations and Fields",
      "Get Data and Memory Tables",
      "In-Memory xvelocity Database",
      "Table and Tree Map Visuals",
      "Format Button and Data Labels",
      "Legend, Category and Grid",
      "PBIX and PBIT File Formats",
      "Visual Interaction, Data Points",
      "Disabling Visual Interactions",
      "Edit Interactions - Format Options",
      "SPOTLIGHT & FOCUSMODE",
      "CSV and PDF Exports. Tooltips",
      "Power BI Ecosystem, Architecture",
    ],
    part4: "Visual Sync, Grouping",
    topic4: [
      "Slicer Visual: Real-time Usage",
      "Orientation, Selection Properties",
      "Single & Multi Select, CTRL Options",
      "Slicer: Number, Text and Date Data",
      "Slicer List and Slicer Dropdowns",
      "Visual Sync Limitations with Slicer",
      "Disabling Slicers, Clear Selections",
      "Grouping: Real-time Use, Examples",
      "List Grouping and Binning Options",
      "Grouping Static / Fixed Data Values",
      "Grouping Dynamic / Changing Data",
      "Bin Size and Bin Limits (Max, Min)",
      "Bin Count and Grouping Options",
      "Grouping Binned Data, Classification",
    ],
    part5: "Hierarchies, Filters",
    topic5: [
      "Creating Hierarchies in Power BI",
      "Independent Drill-Down Options",
      "Dependent Drill-Down Options",
      "Conditional Drilldowns, Data Points",
      "Drill Up Buttons and Operations",
      "Expand & Show Next Level Options",
      "Dynamic Data Drills Limitations",
      "Show Data and See Records",
      "Filters: Types and Usage in Real-time",
      "Visual Filter, Page Filter, Report Filter",
      "Basic, Advanced and TOP N Filters",
      "Category and Summary Level Filters",
      "DrillThru Filters, Drill Thru Reports",
      "Keep All Filters' Options in Drill Thru",
      "Cross Report Filters, Include, Exclude",
    ],
    part6: "Bookmarks, Azure, Modeling",
    topic6: [
      "Drill-thru Filters, Page Navigations",
      "Bookmarks: Real-time Usage",
      "Bookmarks for Visual Filters",
      "Bookmarks for Page Navigations",
      "Selection Pane with Bookmarks",
      "Buttons, Images with Actions",
      "Buttons, Actions and Text URLs",
      "Bookmarks View & Selection Pane",
      "OLTP Databases, Big Data Sources",
      "Azure Database Access, Reports",
      "Import & Direct Query with Power BI",
      "SQL Queries and Enter Data",
      "Data Modelling: Currency, Relations",
      "Summary, Format, Synonyms",
      "Web View & Mobile View in PBI",
    ],
    part7: "Visualization Properties",
    topic7: [
      "Stacked Charts and Clustered Charts",
      "Line Charts, Area Charts, Bar Charts",
      "100% Stacked Bar & Column Charts",
      "Map Visuals: Tree, Filled, Bubble",
      "Cards, Funnel, Table, Matrix",
      "Scatter Chart: Play Axis, Labels",
      "Series Clusters & Selections",
      "Waterfall Chart and ArcGIS Maps",
    ],
    part8: "Power Query Level 1",
    topic8: [
      "Power Query M Language Purpose",
      "Power Query Architecture and ETL",
      "Data Types, Literals and Values",
      "Power Query Transformation Types",
      "Table & Column Transformations",
      "Text & Number Transformations",
      "Date, Time and Structured Data",
      "List, Record and Table Structures",
      "let, source, in statements @ M Lang",
      "Power Query Functions, Parameters",
      "Invoke Functions, Execution Results",
      "Get Data, Table Creations and Edit",
      "Merge and Append Transformations",
      "Join Kinds, Advanced Editor, Apply",
      "ETL Operations with Power Query",
    ],
    part9: "Power Query Level 2",
    topic9: [
      "Query Duplicate, Query Reference",
      "Group By and Advanced Options",
      "Aggregations with Power Query",
      "Transpose, Header Row Promotion",
      "Reverse Rows and Row Count",
      "Data Type Changes & Detection",
      "Replace Columns: Text, NonText",
      "Replace Nulls: Fill Up, Fill Down",
      "PIVOT, UNPIVOT Transformations",
      "Move Column and Split Column",
      "Extract, Format and Numbers",
      "Date & Time Transformations",
      "Deriving Year, Quarter, Month, Day",
      "Add Column: Query Expressions",
      "Query Step Inserts and Step Edits",
    ],
    part10: "Power Query Level 3",
    topic10: [
      "Creating Parameters in Power Query",
      "Parameter Data Types, Default Lists",
      "Static/Dynamic Lists For Parameters",
      "Removing Columns and Duplicates",
      "Convert Tables to List Queries",
      "Linking Parameters to Queries",
      "Testing Parameters and PBI Canvas",
      "Multi-Valued Parameter Lists",
      "Creating Lists in Power Query",
      "Converting Lists to Table Data",
      "Advanced Edits and Parameters",
      "Data Type Conversions, Expressions",
      "Columns From Examples, Indexes",
      "Conditional Columns, Expressions",
    ],
    part11: "DAX Functions - Level 1",
    topic11: [
      "DAX: Importance in Real-time",
      "Real-world usage of Excel, DAX",
      "DAX Architecture, Entity Sets",
      "DAX Data Types, Syntax Rules",
      "DAX Measures and Calculations",
      "ROW Context and Filter Context",
      "DAX Operators, Special Characters",
      "DAX Functions, Types in Real-time",
      "Vertipaq Engine, DAX Cheat Sheet",
      "Creating, Using Measures with DAX",
      "Creating, Using Columns with DAX",
      "Quick Measures and Summaries",
      "Validation Errors, Runtime Errors",
      "SUM, AVERAGEX, KEEPFILTERS",
      "Dynamic Expressions, IF in DAX",
    ],
    part12: "DAX Functions - Level 2",
    topic12: [
      "Data Modelling Options in DAX",
      "Detecting Relations for DAX",
      "Using Calculated Columns in DAX",
      "Using Aggregated Measures in DAX",
      "Working with Facts & Measures",
      "Modelling: Missing Relations",
      "Modelling: Relation Management",
      "CALCULATE Function Conditions",
      "CALCULATE & ALL Member Scope",
      "RELATED & COUNTROWS in DAX",
      "Entity Sets and Slicing in DAX",
      "Dynamic Expressions, RETURN",
      "Date, Time and Text Functions",
      "Logical, Mathematical Functions",
      "Running Total & EARLIER Function",
    ],
    part13: "DAX Functions Level 3",
    topic13: [
      "Connection with CSV, MS Access",
      "AVERAGEX and AVERAGE in DAX",
      "KEEPFILTERS and CALCULATE",
      "COUNTROWS, RELATED, DIVIDE",
      "PARALLELPERIOD, DATEDADD",
      "CALCULATE & PREVIOUSMONTH",
      "USERELATIONSHIP, DAX Variables",
      "TOTALYTD , TOTALQTD",
      "DIVIDE, CALCULATE, Conditions",
      "IF..ELSE..THEN Statement",
      "SELECTEDVALUE, FORMAT",
      "SUM, DATEDIFF Examples in DAX",
      "TODAY, DATE, DAY with DAX",
      "Time Intelligence Functions — DAX",
    ],
    part14: "Power BI Cloud - 1",
    topic14: [
      "Power BI Service Architecture",
      "Power BI Cloud Components, Use",
      "App Workspaces, Report Publish",
      "Reports & Related Datasets Cloud",
      "Creating New Reports in Cloud",
      "Report Publish and Report Uploads",
      "Dashboards Creation and Usage",
      "Adding Tiles to Dashboards",
      "Pinning Visuals and Report Pages",
      "Visual Pin Actions in Dashboards",
      "LIVE Page Interaction in Dashboard",
      "Adding Media: Images, Custom Links",
      "Adding Charts and Embed Links",
      "API Data Sources, Streaming Data",
      "Streaming Dataset Tiles (REST API)",
    ],
    part15: "Power BI Cloud - 2",
    topic15: [
      "Dashboards Actions, Report Actions",
      "Dataset Actions: Create Report",
      "Share, Metrics and Exports",
      "Mobile View & Dashboard Themes",
      "Q&A [Cortana] and Pin Visuals",
      "Export, Subscribe, Subscribe",
      "Favorite, Insights, Embed Code",
      "Featured Dashboards and Refresh",
      "Gateways Configuration, PBI Service",
      "Gateway Types, Cloud Connections",
      "Gateway Clusters, Add Data Sources",
      "Data Refresh: Manual, Automatic",
      "PBIEngw Service, ODG Logs, Audits",
      "DataFlows, Power Query Expressions",
      "Adding Entities and JSON Files",
    ],
    part16: "Excel & RLS",
    topic16: [
      "Import and Upload Options in Excel",
      "Excel Workbooks and Dashboards",
      "Datasets in Excel and Dashboards",
      "Using Excel Analyzer in Power BI",
      "Using Excel Publisher in PBI Cloud",
      "Excel Workbooks, PINS in Power BI",
      "Excel ODC Connections, Power Pivot",
      "Row Level Security (RLS) with DAX",
      "Need for RLS in Power BI Cloud",
      "Data Modeling in Power BI Desktop",
      "DAX Roles Creation and Testing",
      "Adding Power BI Users to Roles",
      "Custom Visualizations in Cloud",
      "Histogram, Gantt Chart, Infographics",
    ],
    part17: "Report Server, RDL",
    topic17: [
      "Need for Report Server in PROD",
      "Install, Configure Report Server",
      "Report Server DB, Temp Database",
      "Web service URL, Webportal URL",
      "Creating Hybrid Cloud with Power BI",
      "Using Power BI DesktopRS",
      "Uploading Interactive Reports",
      "Report Builder For Report Server",
      "Report Builder For Power BI Cloud",
      "Designing Paginated Reports (RDL)",
      "Deploy to Power BI Report Server",
      "Data Source Connections, Report",
      "Power BI Report Server to Cloud",
      "Tenant IDs Generation and Use",
      "Mobile Report Publisher, Usage",
    ],
    part18: "PowerApp Overview",
    topic18: [
      "Basic Power App Concept",
      "Canvas Apps | Navigation | Customization",
      "Contents (Galleries, Data Cards, Forms, Triggers, Functions & Formulas, Edit Forms, Text Boxes)",
    ],
    part19: "Power BI Service & Power BI Mobile",
    topic19: [
      "Why Power BI Service?",
      "Comparison Power BI Free & Premium",
      "Logging into Power BI Service",
      "Interface overview",
      "Importing data from Desktop to Service",
      "Dataset menu",
      "Working on reports",
      "Dashboard overview",
      "Workspace & Gateways",
      "Installing Gateways - Personal & On-premise",
      "Working alone or collaborating with colleagues",
      "Collaborating in App Workspace",
      "Sharing the results",
      "Publishing the app",
      "Content packs from online services",
      "Power BI Mobile Overview",
      "Excluding dataset from sharing",
    ],
    part20: "Power BI and Excel Together",
    topic20: [
      "Options for Publishing from Excel",
      "Pin Excel Elements to Power BI",
      "Analyze in Excel (Power BI Pro or Premium)",
      "Excel Publish: Upload and Export to Power BI",
      "Sharing Published Excel Dashboards (Power BI Pro or Premium)",
    ],
    part21: "Real-Time Project",
    topic21: [
      "Project Requirement Analysis",
      "Implementing SDLC Phases",
      "Requirement Gathering, FSA",
      "Phase 1: PBIX Report Design",
      "Visualizations, Properties",
      "Analytics and Formatting",
      "Phase 2: Data modelling, Power Query",
      "Dynamic Connections, Azure DB",
      "Parameters and M Lang Scripts",
      "Phase 3: DAX Requirements, Analysis",
      "Cloud and Report Server",
      "Project FAQs and Solutions",
    ],
  };

  const Informatica = {
    title: "Informatica",
    part1: "Introduction to Informatica",
    topic1: [
      "Overview of Data Integration",
      "Introduction to ETL (Extract, Transform, Load)",
      "Informatica PowerCenter Overview",
      "Informatica Architecture",
      "Informatica Client Tools",
      "Informatica Repository and PowerHub",
    ],
    part2: "Informatica Workflow and Session",
    topic2: [
      "Creating and Managing Sessions",
      "Understanding Workflows",
      "Running and Monitoring Sessions",
      "Session Properties and Configuration",
      "Error Handling in Workflows",
      "Session Log Files",
      "Debugging Workflows",
    ],
    part3: "Informatica Transformations",
    topic3: [
      "Overview of Transformations",
      "Source Qualifier Transformation",
      "Aggregator Transformation",
      "Expression Transformation",
      "Lookup Transformation",
      "Joiner Transformation",
      "Filter and Router Transformations",
      "Sorter Transformation",
      "Update Strategy Transformation",
      "Union Transformation",
    ],
    part4: "Informatica Data Quality",
    topic4: [
      "Introduction to Data Quality",
      "Data Profiling and Cleansing",
      "Data Standardization",
      "Address Validation",
      "Data Matching",
      "Data Enrichment",
      "Data Transformation Rules",
    ],
    part5: "Informatica PowerExchange",
    topic5: [
      "Introduction to PowerExchange",
      "Real-Time Data Integration",
      "Configuring PowerExchange for Source and Target Systems",
      "PowerExchange for Mainframe Integration",
      "PowerExchange for Cloud Integration",
      "Change Data Capture (CDC)",
      "CDC Best Practices",
    ],
    part6: "Informatica Cloud",
    topic6: [
      "Overview of Informatica Cloud",
      "Setting up Informatica Cloud",
      "Cloud Data Integration",
      "Cloud Application Integration",
      "Cloud Data Quality",
      "Cloud Data Governance",
      "Informatica Cloud Secure Agent",
      "Data Migration to Cloud",
    ],
  };

  const Pega = {
    title: "PEGA Course Content",
    part1: "Understanding Core Part of PEGA PRPC",
    topic1: [
      "PEGA BPM Demo",
      "About PRPC IDE, Operators (Logins)",
      "Creating a new Application using application Wizard",
      "Class Group and Its importance, Understanding Class Group and Predefined Classes in PEGA",
      "Inheritance in PEGA and its Types, Direct and Pattern Inheritance",
      "Working with User Interface in PEGA",
      "Web Page Creating and Executing its execution using a flow",
    ],
    part2: "Working with Properties and User Interface",
    topic2: [
      "Understanding Property and Property rule form",
      "Understanding User Interface Design Using Sections",
      "Understanding Flow Action",
      "Understanding PRPC Process Flows",
      "Creating a Work Object and Understanding the Work Object",
      "Changing the WO Status using Assignment Shape",
    ],
    part3: "Debugging and Activity Concepts",
    topic3: [
      "Understanding the Debugging Tools",
      "Clipboard",
      "Where Am I?",
      "Understanding the System Created User Page 'pyWorkPage'",
      "Creating a UI Form, Displaying the Layout and controls conditionally",
      "Creating a Multi Layout Section",
      "Creating a Section with Dynamic and Free Form Layouts",
      "Understanding 'When' Condition",
      "Creating and Using When rule in the Visibility of layouts and properties",
    ],
    part4: "Working with Business Logic in PEGA",
    topic4: [
      "Introduction to Business Logic by Using Activity",
      "Creating Activity",
      "Understanding User Pages, steps and Basic Methods in Activities like Page-New, Property-Set, Page-Remove, and Show-Page",
      "Visiting the Debugging Tool 'Tracer' and Understanding the Tracer",
      "Calling One Activity from another activity using Call and Branch Instructions",
      "Understanding the Difference between Call and Branch Instructions",
      "Using and Understanding the Difference between Exit-Activity & End-Activity Methods",
      "Calling or Invoking a Flow from Activity",
      "Parameters in activities and passing parameters from one activity to another activity",
      "Understanding the parameter page on Tracer",
    ],
    part5: "Working with Data and Expressions",
    topic5: [
      "Creating Data Storage Rules, Datatables",
      "Understanding Obj-Save, Cancel and Rollback Methods",
      "Understanding Data- Predefined Class and its importance",
      "Working with Expression Builder",
      "Obj-Save Methods and Differences between WriteNow and Commit Methods",
      "Generating the Primary Key using Expression Builder",
      "Obj-Open using primary key & Obj-Open-by-Handle using pzInsKey",
      "Working with Operator Table by understanding OperatorID Page and Data-Admin-DB-Operator Class",
    ],
    part6: "Advanced Rules and Implementations",
    topic6: [
      "Introducing Data Transform",
      "Customizing the OOTB Data Transform pyDefault",
      "Working with Data Transform",
      "Defaulting Values to Properties using DTF",
      "Understanding when to use activity and when to use Data Transforms",
      "Working with Declarative Rules by integrating with business application",
      "Declare Expressions, Forward Chaining & Backward Chaining",
      "Declare Constraints",
      "Declare OnChange",
      "Working with Property-Set and Page-Set- Messages Methods",
      "Difference between DeclareTrigger and Declare Pages",
    ],
    part7: "Application Development and Enhancement",
    topic7: [
      "Introducing RuleSet and Versioning of Rules",
      "Types of Flows, ProcessFlow, SubFlow and ScreenFlows",
      "Invoking SubFlow or ScreenFlow from Process Flow using SubProcess Shape",
      "Understanding Decision Rules and integrating these into the business application development",
      "Flow Action Types and working with Attachments",
      "Working with Harnesses and customizing them",
      "Working with Dynamic System Settings",
      "Email Integration & Outbound Email Integration",
      "Revisiting the Operator, creating custom operators",
      "Routing & Integrating Routing into Application",
    ],
    part8: "Real-Time Implementation and Deployment",
    topic8: [
      "Enterprise Application Architecture",
      "Methodology and Project Process Explanation",
      "Explanation of How an Application gets triggered in Live (Production) environment",
      "Development, Integration, UAT (User Acceptance Testing) and Production Servers Explanation",
      "Authentication and Authorization process in PEGA",
      "Real-Time Process, Team Structure, Requirement Gathering tools, Deployment Process",
      "Deployment tools and Approvals",
      "Merging of Ruleset Versions, Major and Minor Skimming",
    ],
  };

  const Java = {
    title: "Java Full Stack Development",
    part1: "Introduction to Full Stack Development",
    topic1: [
      "What is Full Stack Development?",
      "Overview of Frontend and Backend Development",
      "Technologies in the Java Full Stack",
      "Introduction to Java Programming",
      "Setting Up Java Development Environment (JDK, IDE)",
      "Version Control with Git and GitHub",
      "Overview of Spring Framework",
      "Introduction to Maven and Gradle",
      "Building a Simple Java Application",
    ],
    part2: "Frontend Development with HTML, CSS, and JavaScript",
    topic2: [
      "Introduction to HTML and CSS",
      "Building Web Pages with HTML5",
      "Styling with CSS3",
      "CSS Flexbox and Grid",
      "Responsive Web Design (Media Queries)",
      "Introduction to JavaScript",
      "Handling Events in JavaScript",
      "DOM Manipulation",
      "ES6 Features (Arrow Functions, Promises, etc.)",
      "JavaScript Frameworks Overview (React, Angular, Vue)",
    ],
    part3: "Frontend Development with React",
    topic3: [
      "Introduction to React",
      "Setting Up React with JSX",
      "Creating Components in React",
      "State and Props in React",
      "React Hooks: useState, useEffect, etc.",
      "Event Handling in React",
      "Building Forms in React",
      "Routing with React Router",
      "State Management with Context API and Redux",
      "Testing React Components with Jest and Enzyme",
    ],
    part4: "Backend Development with Java and Spring Boot",
    topic4: [
      "Introduction to Java Backend Development",
      "Setting Up Spring Boot Application",
      "Creating RESTful APIs with Spring Boot",
      "Spring MVC and Thymeleaf",
      "Data Access with Spring Data JPA",
      "Dependency Injection in Spring",
      "Handling HTTP Requests and Responses",
      "Model-View-Controller (MVC) Architecture",
      "Spring Security for Authentication and Authorization",
      "Spring Boot Profiles and Configuration",
    ],
    part5: "Database Development with MySQL",
    topic5: [
      "Introduction to Relational Databases",
      "Setting Up MySQL Database",
      "Creating and Managing Databases and Tables",
      "Writing SQL Queries (SELECT, INSERT, UPDATE, DELETE)",
      "Joins, Subqueries, and Grouping in SQL",
      "Normalization and Database Design",
      "Stored Procedures and Functions",
      "Introduction to Hibernate ORM",
      "Using JPA (Java Persistence API) with Spring Data",
      "Database Migrations with Flyway",
    ],
    part6: "Working with APIs and Web Services",
    topic6: [
      "Introduction to RESTful APIs",
      "Creating APIs with Spring Boot",
      "Handling JSON and XML Data Formats",
      "API Versioning Strategies",
      "Securing APIs with JWT Authentication",
      "Consuming External APIs with RestTemplate",
      "Error Handling in Spring Boot APIs",
      "File Uploading and Downloading in APIs",
      "Versioning and Documenting APIs with Swagger",
      "Testing RESTful APIs with Postman and JUnit",
    ],
    part7: "Frontend and Backend Integration",
    topic7: [
      "Connecting React with Spring Boot APIs",
      "Managing API Calls with Axios",
      "State Management with Redux and API Integration",
      "Handling Form Submissions and API Calls in React",
      "Implementing Authentication with JWT in React and Spring Boot",
      "Error Handling and Debugging in Full Stack",
      "Data Binding between Frontend and Backend",
      "Real-Time Data with WebSockets and STOMP",
      "Building a Full Stack Application from Scratch",
      "Testing Full Stack Applications",
    ],
    part8: "Cloud Integration with AWS",
    topic8: [
      "Introduction to Cloud Computing",
      "Setting Up AWS Account and Services",
      "AWS EC2 for Hosting Java Applications",
      "AWS RDS for MySQL Database Hosting",
      "AWS S3 for File Storage",
      "AWS Lambda for Serverless Computing",
      "Deploying Full Stack Application on AWS",
      "Securing Applications with AWS IAM",
      "Integrating AWS CloudWatch for Monitoring",
      "CI/CD with AWS CodePipeline and CodeDeploy",
    ],
    part9: "Testing in Java Full Stack Development",
    topic9: [
      "Unit Testing with JUnit and Mockito",
      "Writing Integration Tests for APIs",
      "Testing React Components with Jest",
      "End-to-End Testing with Selenium",
      "Test-Driven Development (TDD) in Full Stack",
      "Mocking Dependencies in Unit Tests",
      "Continuous Testing with Jenkins and GitHub Actions",
      "API Testing with Postman",
      "Testing Database Transactions with Spring",
      "Best Practices for Testing Full Stack Applications",
    ],
    part10: "Performance Optimization and Security",
    topic10: [
      "Optimizing Performance in Spring Boot",
      "Caching in Spring Boot with Ehcache",
      "Database Query Optimization with Hibernate",
      "Load Balancing and Horizontal Scaling",
      "Securing APIs with HTTPS and SSL",
      "SQL Injection Prevention in Java",
      "Cross-Site Scripting (XSS) and CSRF Prevention",
      "Role-Based Access Control (RBAC)",
      "OAuth 2.0 and JWT Authentication",
      "Best Practices for Secure Java Full Stack Development",
    ],
    part11: "Deployment and DevOps",
    topic11: [
      "Introduction to DevOps",
      "Continuous Integration and Continuous Deployment (CI/CD)",
      "Setting Up Jenkins for Full Stack Projects",
      "Dockerizing Java Applications",
      "Building Docker Containers for Full Stack Applications",
      "Deploying Full Stack Applications on AWS EC2",
      "Using Kubernetes for Container Orchestration",
      "Setting Up and Managing CI/CD Pipelines with GitHub Actions",
      "Azure DevOps for Full Stack Projects",
      "Monitoring and Logging with ELK Stack (Elasticsearch, Logstash, Kibana)",
    ],
    part12: "Project and Real-World Applications",
    topic12: [
      "Building a Full Stack Application: A Step-by-Step Guide",
      "Best Practices for Full Stack Development",
      "Collaborative Development and Code Reviews",
      "Building a Real-Time Chat Application",
      "Building an E-commerce Platform with Java and React",
      "Building a Social Media Application",
      "Optimizing and Scaling Full Stack Applications",
      "Project Management and Agile Methodology",
      "Deploying and Maintaining Full Stack Applications",
      "Project Presentation and Demo",
    ],
  };

  const MicroSoft = {
    title: "Microsoft Full Stack Development",
    part1: "Introduction to Full Stack Development",
    topic1: [
      "What is Full Stack Development?",
      "Overview of Frontend and Backend Development",
      "Microsoft Full Stack Overview",
      "Technologies in the Microsoft Stack",
      "Introduction to .NET Framework and .NET Core",
      "Web Development with Microsoft Technologies",
      "Overview of Visual Studio and Visual Studio Code",
      "Setting Up Development Environment",
    ],
    part2: "Frontend Development with React & TypeScript",
    topic2: [
      "Introduction to React and TypeScript",
      "Setting Up React with TypeScript",
      "Creating Components and JSX",
      "State and Props in React",
      "Event Handling in React",
      "Using Hooks: useState, useEffect, etc.",
      "Building Forms and Handling Input",
      "Styling React Components with CSS and CSS-in-JS",
      "React Router and Handling Navigation",
      "Managing State with Context API and Redux",
    ],
    part3: "Backend Development with ASP.NET Core",
    topic3: [
      "Introduction to ASP.NET Core",
      "Setting Up ASP.NET Core Application",
      "MVC Architecture and Razor Pages",
      "Routing and Middleware in ASP.NET Core",
      "Web API Development with ASP.NET Core",
      "Creating and Handling HTTP Requests",
      "Building RESTful APIs",
      "Data Validation and Model Binding",
      "Authentication and Authorization in ASP.NET Core",
      "Integrating with External APIs",
    ],
    part4: "Database Development with SQL Server",
    topic4: [
      "Introduction to SQL Server and Relational Databases",
      "Creating and Managing Databases in SQL Server",
      "Understanding Tables, Views, and Indexes",
      "Writing SQL Queries (SELECT, INSERT, UPDATE, DELETE)",
      "Using Joins, Subqueries, and Aggregation Functions",
      "Stored Procedures and Functions",
      "Database Normalization and Design Principles",
      "Entity Framework Core for ORM",
      "Migrations and Data Seeding in EF Core",
      "Performing CRUD Operations with EF Core",
    ],
    part5: "Working with APIs and Web Services",
    topic5: [
      "Creating and Consuming APIs in ASP.NET Core",
      "Introduction to RESTful APIs",
      "CRUD Operations with Web API",
      "API Versioning and Documentation",
      "Securing APIs with JWT Authentication",
      "Consuming External APIs using HttpClient",
      "Error Handling and Logging in Web API",
      "Handling CORS in ASP.NET Core",
      "Testing APIs with Postman",
      "Building GraphQL APIs with ASP.NET Core",
    ],
    part6: "Frontend and Backend Integration",
    topic6: [
      "Connecting React with ASP.NET Core Web API",
      "Creating Data Models in React and ASP.NET Core",
      "Fetching Data from API and Rendering in React",
      "Handling Form Submissions in React and ASP.NET Core",
      "Implementing Authentication with JWT",
      "State Management with Redux and API Calls",
      "Handling HTTP Requests with Axios",
      "Working with WebSockets for Real-Time Data",
      "Error Handling and Debugging",
      "Deploying Full Stack Application Locally and on the Web",
    ],
    part7: "Cloud Integration with Azure",
    topic7: [
      "Introduction to Microsoft Azure",
      "Setting Up an Azure Account",
      "Azure App Services and Hosting Web Applications",
      "Azure SQL Database and Connectivity",
      "Azure Blob Storage and File Management",
      "Azure Functions for Serverless Computing",
      "Deploying ASP.NET Core Apps to Azure",
      "Authentication and Authorization with Azure Active Directory",
      "Continuous Integration and Deployment with Azure DevOps",
      "Monitoring and Managing Azure Resources",
    ],
    part8: "Testing in Full Stack Development",
    topic8: [
      "Unit Testing in ASP.NET Core",
      "Mocking Dependencies with Moq",
      "Writing Unit Tests with xUnit",
      "Testing React Components with Jest and Enzyme",
      "Integration Testing in ASP.NET Core",
      "Test-Driven Development (TDD) in Full Stack",
      "End-to-End Testing with Selenium",
      "Continuous Testing with Azure DevOps Pipelines",
      "Automating Test Execution with GitHub Actions",
      "Best Practices for Testing Full Stack Applications",
    ],
    part9: "Performance Optimization and Security",
    topic9: [
      "Optimizing Performance in ASP.NET Core",
      "Caching Strategies in ASP.NET Core",
      "Load Balancing and Scalability",
      "Database Query Optimization",
      "Securing APIs with HTTPS and CORS",
      "SQL Injection Prevention",
      "Cross-Site Scripting (XSS) and Cross-Site Request Forgery (CSRF)",
      "Role-Based Access Control (RBAC)",
      "Securing React Applications with OAuth2",
      "Best Practices for Secure Full Stack Development",
    ],
    part10: "Deployment and DevOps",
    topic10: [
      "Introduction to DevOps",
      "Continuous Integration and Continuous Deployment (CI/CD)",
      "Setting Up Azure DevOps for Full Stack Projects",
      "Automating Deployments with Azure Pipelines",
      "Deploying React Applications to Azure App Service",
      "Deploying ASP.NET Core APIs to Azure",
      "Containerization with Docker",
      "Orchestration with Kubernetes on Azure",
      "Monitoring Applications with Azure Monitor",
      "Maintaining and Updating Deployed Applications",
    ],
    part11: "Project and Real-World Applications",
    topic11: [
      "Building a Full Stack Application: A Step-by-Step Guide",
      "Best Practices for Full Stack Development",
      "Version Control with Git and GitHub",
      "Collaboration and Code Review in Full Stack Teams",
      "Handling Real-World Challenges in Full Stack Development",
      "Implementing a Real-Time Chat Application",
      "Building an E-commerce Application with React and ASP.NET Core",
      "Building a Social Media Platform with Full Stack Technologies",
      "Optimizing and Scaling Full Stack Applications",
      "Project Presentation and Demo",
    ],
  };

  const Testing = {
    title: "Testing Manual & Automation",
    part1: "Introduction to Software Testing",
    topic1: [
      "What is Software Testing?",
      "Importance of Software Testing",
      "Testing Life Cycle",
      "Types of Software Testing (Manual and Automated)",
      "Testing Levels: Unit, Integration, System, and Acceptance",
      "Defect Life Cycle",
      "Test Planning and Strategy",
      "Test Case Design and Documentation",
    ],
    part2: "Manual Testing Fundamentals",
    topic2: [
      "Introduction to Manual Testing",
      "Understanding Requirements and Test Scenarios",
      "Test Case Development and Execution",
      "Black Box Testing: Functional Testing",
      "White Box Testing: Structural Testing",
      "Exploratory Testing",
      "Regression and Retesting",
      "Defect Reporting and Tracking",
    ],
    part3: "Types of Manual Testing",
    topic3: [
      "Functional Testing",
      "Non-Functional Testing (Performance, Security, Usability)",
      "Acceptance Testing",
      "Smoke and Sanity Testing",
      "Integration Testing",
      "System Testing",
      "User Interface (UI) Testing",
      "Alpha and Beta Testing",
    ],
    part4: "Introduction to Automation Testing",
    topic4: [
      "What is Automation Testing?",
      "Benefits and Challenges of Automation",
      "Automation Testing Tools Overview",
      "When to Automate vs. Manual Testing",
      "Automation Testing Life Cycle",
      "Test Automation Strategy and Framework",
      "Introduction to Test Scripts and Tools",
      "Scripting Languages for Automation (Java, Python, JavaScript)",
    ],
    part5: "Automation Testing Tools",
    topic5: [
      "Introduction to Selenium WebDriver",
      "Setting Up Selenium WebDriver",
      "Writing First Selenium Test Script",
      "Using XPath and CSS Selectors in Selenium",
      "Introduction to TestNG for Test Automation",
      "Data-Driven Testing in Selenium",
      "Integrating Selenium with Maven and Jenkins",
      "Using Other Automation Tools (QTP, JMeter, Appium)",
    ],
    part6: "Creating Test Automation Framework",
    topic6: [
      "What is a Test Automation Framework?",
      "Types of Test Automation Frameworks (Data-Driven, Keyword-Driven, Hybrid)",
      "Setting Up TestNG with Maven",
      "Page Object Model (POM) for Test Automation",
      "Handling Synchronization Issues in Automation",
      "Working with Test Data and External Sources",
      "Integrating Test Automation with Continuous Integration (CI)",
      "Reporting and Log Management in Automation",
    ],
    part7: "Performance Testing",
    topic7: [
      "What is Performance Testing?",
      "Performance Testing Tools Overview (JMeter, LoadRunner)",
      "Types of Performance Testing: Load, Stress, and Scalability",
      "Creating Performance Test Plans and Scenarios",
      "Executing Performance Tests with JMeter",
      "Analyzing Performance Test Results",
      "Performance Bottlenecks and Optimization",
      "Integrating Performance Testing with Automation",
    ],
    part8: "Security and Penetration Testing",
    topic8: [
      "Introduction to Security Testing",
      "Types of Security Testing (Vulnerability, Penetration Testing)",
      "Common Security Vulnerabilities (SQL Injection, Cross-Site Scripting)",
      "Security Testing Tools (OWASP ZAP, Burp Suite)",
      "Creating Security Test Plans and Scenarios",
      "Manual vs. Automated Security Testing",
      "Security Automation with Tools like Selenium",
      "Best Practices for Security Testing",
    ],
    part9: "Mobile Application Testing",
    topic9: [
      "Introduction to Mobile Testing",
      "Types of Mobile Application Testing (Functional, Usability, Performance)",
      "Mobile Testing Tools Overview (Appium, Espresso)",
      "Manual Mobile Testing Techniques",
      "Automated Mobile Testing with Appium",
      "Emulator/Simulator vs. Real Device Testing",
      "Mobile Automation Frameworks",
      "Handling Mobile-Specific Issues in Automation",
    ],
    part10: "Continuous Integration and Continuous Testing",
    topic10: [
      "Introduction to Continuous Integration (CI)",
      "CI/CD Pipeline Overview",
      "Integrating Automation Testing with CI/CD",
      "Using Jenkins for Continuous Integration",
      "Automating Test Execution in CI",
      "Reporting Test Results in CI",
      "Best Practices for Continuous Testing",
      "Managing Test Environments in CI/CD",
    ],
    part11: "Best Practices in Software Testing",
    topic11: [
      "Best Practices for Manual Testing",
      "Best Practices for Automated Testing",
      "Choosing the Right Test Automation Tool",
      "Test Data Management",
      "Maintaining Test Scripts and Frameworks",
      "Test Reporting and Metrics",
      "Collaboration between Developers and Testers",
      "Test Maintenance and Refactoring",
    ],
  };

  const Aws = {
    title: "AWS DevOps",
    part1: "Introduction to DevOps and AWS",
    topic1: [
      "Overview of DevOps",
      "DevOps Life Cycle",
      "DevOps Practices",
      "AWS Overview and Services",
      "Setting Up AWS Account",
      "Overview of AWS EC2, S3, IAM, VPC",
      "AWS CLI and SDK Setup",
      "AWS Management Console",
    ],
    part2: "Source Control and Continuous Integration",
    topic2: [
      "Introduction to Version Control (Git)",
      "Setting up Git on AWS EC2",
      "Using GitHub/GitLab for Source Code Management",
      "Continuous Integration Overview",
      "Setting up Jenkins on AWS EC2",
      "Integrating Jenkins with GitHub",
      "Jenkins Pipeline and Job Configuration",
      "Automated Testing with Jenkins",
      "AWS CodeCommit and CodePipeline",
    ],
    part3: "Configuration Management",
    topic3: [
      "Introduction to Configuration Management",
      "Using AWS Systems Manager",
      "Automating Infrastructure with AWS CloudFormation",
      "AWS OpsWorks",
      "Ansible for Configuration Management",
      "Chef for Configuration Management",
      "Puppet for Automation",
      "Automating Server Provisioning",
    ],
    part4: "Continuous Delivery and Deployment",
    topic4: [
      "Continuous Delivery Overview",
      "AWS CodeDeploy",
      "AWS Elastic Beanstalk for Application Deployment",
      "Blue/Green Deployment Strategy",
      "Canary Deployment",
      "Rolling Updates",
      "Automating Deployment with Jenkins and AWS CodeDeploy",
      "Managing Deployment Pipelines",
    ],
    part5: "Monitoring, Logging, and Security",
    topic5: [
      "AWS CloudWatch for Monitoring",
      "AWS CloudTrail for Logging",
      "Setting up Alarms and Notifications",
      "Metrics and Dashboard Creation in CloudWatch",
      "Log Aggregation and Analysis with CloudWatch Logs",
      "Security Best Practices in AWS",
      "IAM Policies and Roles",
      "AWS Security Hub and AWS Config",
      "Secure DevOps with AWS",
    ],
    part6: "Infrastructure as Code (IaC)",
    topic6: [
      "Introduction to Infrastructure as Code",
      "AWS CloudFormation for IaC",
      "Creating and Managing Stacks with CloudFormation",
      "AWS CDK (Cloud Development Kit)",
      "Terraform for IaC",
      "Provisioning Infrastructure with Terraform",
      "Managing State in Terraform",
      "Version Control for IaC",
    ],
    part7: "Scalability, High Availability, and Disaster Recovery",
    topic7: [
      "AWS Auto Scaling and Load Balancing",
      "Elastic Load Balancer (ELB)",
      "AWS EC2 Auto Scaling",
      "Creating Highly Available Architectures",
      "AWS Multi-AZ and Multi-Region Deployments",
      "Disaster Recovery Strategies in AWS",
      "Backup and Restore Strategies",
      "AWS Route 53 for DNS Failover",
    ],
    part8: "Cost Optimization and Best Practices",
    topic8: [
      "AWS Cost and Usage Reports",
      "Cost Optimization Techniques",
      "AWS Trusted Advisor and Cost Explorer",
      "Optimizing EC2, S3, and RDS Costs",
      "AWS Reserved Instances and Spot Instances",
      "AWS Cost Management Tools",
      "Security Best Practices for Cost Optimization",
    ],
  };

  const Azure = {
    title: "Azure DevOps",
    part1: "Introduction to DevOps and Azure",
    topic1: [
      "Overview of DevOps",
      "DevOps Life Cycle",
      "DevOps Practices and Principles",
      "Azure Overview and Services",
      "Setting up Azure Account",
      "Azure DevOps Overview",
      "Azure Resource Manager (ARM)",
      "Azure CLI and PowerShell Setup",
      "Azure Management Portal",
    ],
    part2: "Source Control and Continuous Integration",
    topic2: [
      "Introduction to Version Control (Git)",
      "Setting up Git in Azure Repos",
      "Using GitHub and Azure Repos for Source Code Management",
      "Continuous Integration Overview",
      "Setting up Azure Pipelines",
      "Building a CI Pipeline in Azure DevOps",
      "Integrating Azure Pipelines with GitHub",
      "Automated Testing with Azure Pipelines",
      "Managing Branches and Pull Requests",
    ],
    part3: "Configuration Management",
    topic3: [
      "Introduction to Configuration Management",
      "Using Azure Automation for Configuration Management",
      "Infrastructure Automation with ARM Templates",
      "Azure DevTest Labs",
      "Using Azure Resource Manager Templates",
      "Ansible for Configuration Management",
      "Chef and Puppet Integration with Azure",
      "Managing Infrastructure as Code (IaC) in Azure",
    ],
    part4: "Continuous Delivery and Deployment",
    topic4: [
      "Continuous Delivery Overview",
      "Azure Pipelines for Continuous Deployment",
      "Creating and Managing Release Pipelines",
      "Azure Web Apps for Deployment",
      "Blue/Green Deployment in Azure",
      "Canary Deployment Strategy in Azure",
      "Managing Deployment and Release Gates",
      "Rollback Strategies in Azure DevOps",
    ],
    part5: "Monitoring, Logging, and Security",
    topic5: [
      "Azure Monitor for Monitoring",
      "Azure Log Analytics and Application Insights",
      "Setting up Alerts and Notifications in Azure Monitor",
      "Azure Security Center for Security Management",
      "Managing Azure Resources with Role-Based Access Control (RBAC)",
      "Security Best Practices in Azure DevOps",
      "Audit Logs and Compliance in Azure",
    ],
    part6: "Infrastructure as Code (IaC)",
    topic6: [
      "Introduction to Infrastructure as Code",
      "Azure Resource Manager (ARM) Templates",
      "Creating and Managing ARM Templates",
      "Azure DevOps and Infrastructure Automation",
      "Using Terraform with Azure",
      "Managing Infrastructure with Terraform",
      "Azure DevOps Pipelines for IaC",
      "Version Control for ARM Templates",
    ],
    part7: "Scalability, High Availability, and Disaster Recovery",
    topic7: [
      "Azure Auto Scaling and Load Balancing",
      "Azure Load Balancer and Application Gateway",
      "Scaling Azure Web Apps and Virtual Machines",
      "Azure Availability Sets and Zones",
      "Designing for High Availability in Azure",
      "Disaster Recovery Strategies in Azure",
      "Azure Backup and Site Recovery",
      "Azure Traffic Manager for DNS Failover",
    ],
    part8: "Cost Optimization and Best Practices",
    topic8: [
      "Azure Cost Management and Pricing Calculator",
      "Cost Optimization Strategies in Azure",
      "Azure Advisor Recommendations",
      "Optimizing Azure Storage, Compute, and Networking Costs",
      "Azure Reserved Instances and Spot VMs",
      "Scaling and Auto-scaling to Reduce Costs",
      "Managing Resources with Azure Tags and Policies",
      "Using Azure DevOps for Cost-Effective Solutions",
    ],
  };

  const Tableau = {
    title: "Tableau",
    part1: "Introduction to Tableau",
    topic1: [
      "Overview of Data Visualization",
      "Introduction to Tableau Software",
      "Tableau Editions: Desktop, Server, Online",
      "Tableau Interface and Navigation",
      "Connecting to Data Sources",
      "Importing Data into Tableau",
      "Data Types and Data Structures in Tableau",
      "Understanding Tableau File Formats (.twb, .twbx)",
    ],
    part2: "Working with Data in Tableau",
    topic2: [
      "Data Connection Types (Excel, CSV, Databases)",
      "Data Blending and Joins",
      "Filtering Data in Tableau",
      "Grouping and Hierarchies",
      "Data Preparation with Tableau Prep",
      "Creating and Managing Data Extracts",
      "Data Source Management",
      "Using Calculated Fields and Formulas",
    ],
    part3: "Building Basic Visualizations",
    topic3: [
      "Creating Basic Charts (Bar, Line, Scatter)",
      "Working with Dimensions and Measures",
      "Building Pie Charts and Histograms",
      "Creating Stacked Bar and Area Charts",
      "Dual-axis and Combination Charts",
      "Using Geographic Data and Maps in Tableau",
      "Creating Heat Maps and Tree Maps",
      "Sorting and Formatting Visualizations",
    ],
    part4: "Advanced Visualization Techniques",
    topic4: [
      "Creating Dashboards in Tableau",
      "Using Filters and Parameters",
      "Dynamic Dashboards with Actions",
      "Using Trend Lines and Reference Lines",
      "Forecasting and Predictive Analysis",
      "Creating Advanced Calculations (LOD, Table Calculations)",
      "Customizing Visualizations with Tableau Extensions",
      "Working with Custom Views and Tooltips",
    ],
    part5: "Data Analysis and Exploration",
    topic5: [
      "Exploratory Data Analysis (EDA) with Tableau",
      "Statistical Analysis using Tableau",
      "Data Aggregation and Granularity",
      "What-If Analysis with Parameters",
      "Creating Cohort Analysis",
      "Performing Time Series Analysis",
      "Data Relationships and Correlations",
      "Creating Dynamic and Interactive Dashboards",
    ],
    part6: "Tableau Prep and Data Shaping",
    topic6: [
      "Introduction to Tableau Prep Builder",
      "Data Cleaning with Tableau Prep",
      "Shaping and Pivoting Data in Tableau Prep",
      "Merging and Joining Data in Tableau Prep",
      "Handling Null Values and Missing Data",
      "Creating and Saving Flow Files",
      "Exporting Data from Tableau Prep",
      "Integrating Tableau Prep with Tableau Desktop",
    ],
    part7: "Publishing and Sharing Visualizations",
    topic7: [
      "Publishing Workbooks to Tableau Server and Tableau Online",
      "Sharing Dashboards and Visualizations",
      "Embedding Tableau Visualizations in Webpages",
      "Setting Permissions and Security for Tableau Workbooks",
      "Scheduling and Automating Refreshes in Tableau Server",
      "Creating Subscriptions for Reports and Dashboards",
      "Exploring Tableau Public for Sharing Dashboards",
      "Version Control and Collaboration in Tableau",
    ],
    part8: "Advanced Features and Customization",
    topic8: [
      "Working with Tableau Server and Tableau Online",
      "Creating Custom Calculations using Tableau Scripting",
      "Connecting to Big Data Sources (Hadoop, Spark)",
      "Tableau REST API for Custom Integrations",
      "Integrating Tableau with R and Python for Advanced Analytics",
      "Creating Custom Visualizations and Extensions",
      "Performance Optimization in Tableau",
      "Tableau Best Practices for Visualization Design",
    ],
  };

  const Sql = {
    title: "SQL",
    part1: "Introduction to Basic Database Concepts",
    topic1: [
      "What is Data, Field, Record and Database?",
      "Limitations of File Management System",
      "Basic Concepts of Advantages of DBMS",
      "Levels of Abstraction",
      "Database Models",
      "Exploring Relational DBMS",
      "Understanding Client and Server",
    ],
    part2: "E-R Modeling and Diagram",
    topic2: [
      "Analyzing the Requirement",
      "Identify Entities and their Relationships",
      "Drawing E-R Diagram",
      "Conversion of E.R. Diagrams into Tables",
    ],
    part3: "Normalization",
    topic3: [
      "First Normal Form",
      "Second Normal Form",
      "Third Normal Form",
      "Practically Normalizing Tables",
    ],
    part4: "Introduction to SQL Server",
    topic4: [
      "History of SQL Server",
      "Types of System Databases",
      "Communication Between Frontend and Backend",
      "SQL Server Versions and Editions",
      "Basic Features, Components, and Tools",
      "Starting and Stopping SQL Server Instances/Services",
      "Introduction to Management Studio",
    ],
    part5: "Introduction to SQL",
    topic5: [
      "Basics of SQL",
      "Types of SQL Statements (DDL, DML, DQL, DCL, TCL)",
      "Create Database using Management Studio",
      "Datatypes in SQL Server",
      "Exploring DDL Statements on Table using Management Studio",
    ],
    part6: "DDL and DML Statements",
    topic6: [
      "Create, Alter, and Drop Table",
      "Insert, Update, and Delete Statements",
      "Truncate Statement",
    ],
    part7: "Working with Queries (DQL)",
    topic7: [
      "Understanding Select Statement",
      "Usage of Top, Distinct, Null, etc. Keywords",
      "Using String and Arithmetic Expressions",
      "Exploring Where Clause with Operators",
      "Using Advanced Operators",
      "Sorting Data using Order By Clause",
      "Working with Basic of Sub Queries",
    ],
    part8: "Aggregate Functions",
    topic8: [
      "Using Functions in Queries",
      "Using Predefined Functions (Count, Sum, Min, Max, Avg)",
      "Group by and Having Clause",
      "Using Group by with Rollup and Cube",
    ],
    part9: "Joins and Set Operations",
    topic9: [
      "Introduction to Joins",
      "Cross Joins",
      "Inner Join",
      "Outer Join",
      "Self Join",
      "Co-related Sub Queries",
      "Set Operations using Unions, Intersect, and Except",
    ],
    part10: "Implementation of Data Integrity",
    topic10: [
      "Entity Integrity",
      "Domain Integrity",
      "Referential Integrity",
      "Types of Constraints",
    ],
    part11: "Working with Constraints",
    topic11: ["Unique", "Not NULL", "Primary Key", "Default Check Foreign Key"],
    part12: "Implementing Views",
    topic12: [
      "Introduction & Advantages of Views",
      "Creating, Altering, Dropping Views",
      "Advanced Options while Creating a View",
      "SQL Server Catalogue Views",
    ],
    part13: "Data Control Language (DCL)",
    topic13: [
      "Creating Users & Roles",
      "Granting & Revoking of Roles & Privileges",
      "Managing using Management Studio",
    ],
    part14: "Working with Indexes",
    topic14: [
      "Introduction to Clustered and Non-Clustered Index",
      "Creating and Dropping Indexes",
    ],
    part15: "Writing Transact-SQL (T-SQL)",
    topic15: [
      "What is T-SQL?",
      "Scripts and Batches",
      "Declaring Variables",
      "Using Statements",
      "Working with Temp Tables",
      "Error Handling",
      "Using System Functions / Global Variables",
      "Using Dynamic SQL",
    ],
    part16: "Working with Stored Procedures and Functions",
    topic16: [
      "Introduction to Stored Procedures",
      "Benefits of Stored Procedures",
      "Creating, Executing, Modifying, Dropping Stored Procedures",
      "Input—Output and Optional Parameters",
      "System Defined SP’s and Functions",
      "User Defined Functions",
    ],
    part17: "Implementing Triggers",
    topic17: [
      "Introduction to Triggers",
      "Constraints vs Triggers",
      "Creating, Altering, Dropping Triggers",
      "For/After/Instead of Triggers",
      "Using Rollback Transaction",
    ],
    part18: "Working with Cursors",
    topic18: [
      "Creating Cursors",
      "Cursors vs. Select",
      "Types of Cursors",
      "Locks on Cursors",
      "Advantages of Cursors",
    ],
    part19: "Transaction Control Language (TCL)",
    topic19: [
      "Introduction to Transactions",
      "Types of Transactions (Implicit, Explicit)",
      "Working with Locks, Types of Locks",
    ],
    part20: "Backup and Restore",
    topic20: [
      "Generating SQL Script",
      "Executing SQL Script",
      "Generating Change Script",
      "Taking Database Backup",
      "Restoring Database using Backup",
    ],
    part21: "Advanced Features",
    topic21: [
      "Pivot Table",
      "Common Table Expression",
      "Ranking Functions",
      "Using BLOB Data Type",
      "Using XML Data Type",
    ],
  };

  return (
    <div>
      <Routes>
        <Route path="/" element={<IndexPage />} />
        <Route path="/about" element={<AboutUsPage />} />
        <Route path="/contact" element={<ContactPage />} />
        <Route path="/our-courses" element={<OurCoursesPage />} />
        <Route path="/gallery" element={<GalleryPage />} />
        <Route path="/blog" element={<BlogPage />} />
        <Route
          path="/python-course"
          element={<PythonCourse prop={pythonData} />}
        />
        <Route
          path="/DataScience"
          element={<DataScienceCourse prop={DataScience} />}
        />
        <Route path="/sql" element={<SqlCourse prop={Sql} />} />
        <Route
          path="/DataAnalytics"
          element={<DataAnalyticsCourse prop={DataAnalytics} />}
        />
        <Route path="/PowerBi" element={<PowerBiCourse prop={PowerBi} />} />
        <Route
          path="/Informatica"
          element={<InformaticaCourse prop={Informatica} />}
        />
        <Route path="/Aws" element={<AwsCourse prop={Aws} />} />
        <Route path="/Azure" element={<AzureCourse prop={Azure} />} />
        <Route path="/Pega" element={<PegaCourse prop={Pega} />} />
        <Route
          path="/MicroSoft"
          element={<MicrosoftCourse prop={MicroSoft} />}
        />
        <Route path="/Java" element={<JavaCourse prop={Java} />} />
        <Route path="/Testing" element={<TestingCourse prop={Testing} />} />
        <Route path="/Sap" element={<SapCourse prop={Sap} />} />
        <Route path="/Tableau" element={<TableauCourse prop={Tableau} />} />
        <Route path="*" element={<NotFound />} />
      </Routes>
    </div>
  );
}

export default App;
